---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ecartcluster1
  region: us-east-2
managedNodeGroups:
  - name: linux-ng
    instanceType: t2.large
    minSize: 2

nodeGroups:
  - name: win-ng
    instanceType: m5.large
    minSize: 2
    volumeSize: 100
    amiFamily: WindowsServer2019FullContainer