---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecartapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecartapi
  template:
    metadata:
      labels:
        app: ecartapi
    spec:
      containers:
      - name: ecartapi
        image: 287782517406.dkr.ecr.us-east-2.amazonaws.com/ecartapi:v4
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80	        
      nodeSelector:
        kubernetes.io/os: windows
        kubernetes.io/arch: "amd64" 
---
apiVersion: v1
kind: Service
metadata:
  name: ecartapi
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: ecartapi