kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: elb-service-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: ecartapi
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: External
    external:
      metricName: request-count
      targetAverageValue: 30